import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, rm, writeFile, access, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { LeaderWorkflow } from "../src/core/workflow.js";
import type { ExecutionReport } from "../src/core/schemas.js";

const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function setup() { const root = await mkdtemp(path.join(os.tmpdir(), "codegate-leader-")); roots.push(root); await writeFile(path.join(root, "task.md"), "Build a reviewed Leader workflow.\n"); const flow = new LeaderWorkflow(root); await flow.intake("task.md"); await flow.approveTask(); await flow.architecture("Boundary", "Keep Leader separate from Coding Agents."); await flow.createPlan(); await flow.approvePlanWithPatch(); return { root, flow }; }
function report(status: "passed" | "failed") : ExecutionReport { return { reportId: `report-${Date.now()}`, stepId: "step-001", handoffVersion: 1, agent: { name: "test" }, status: "completed", summary: "done", filesRead: [], filesChanged: [], commandsRun: [{ command: "test", exitCode: status === "passed" ? 0 : 1, status }], outputs: [], assumptions: [], risks: [], unresolvedItems: [], deviations: [], recommendedNextAction: "review", generatedAt: new Date().toISOString() }; }

describe("CLI Leader workflow", () => {
  it("keeps TaskSpec and WorkPlan version histories immutable", async () => { const { root, flow } = await setup(); const task = await flow.store.task(); const plan = await flow.store.plan(); expect(task).not.toBeNull(); expect(plan).not.toBeNull(); await expect(flow.store.saveTask(task!)).rejects.toThrow("不能重写历史"); await expect(flow.store.savePlan(plan!)).rejects.toThrow("不能重写历史"); await access(path.join(root, ".codegate", "task", "task-spec-v1.json")); await access(path.join(root, ".codegate", "plan", "plan-v2.json")); });
  it("installs selected reusable skills and compiles their method into the Handoff", async () => { const { root, flow } = await setup(); const handoff = await flow.handoff("generic"); expect(handoff.content).toContain("实现交接"); expect(handoff.content).toContain("质量门槛"); await access(path.join(root, ".codegate", "skills", "implementation-handoff-v1.0.0.json")); });
  it("records reported environment facts as pending until the user confirms them", async () => { const { root, flow } = await setup(); await flow.handoff("generic"); const value = report("passed"); value.environmentFacts = { discoveredBy: "test", sourceRevision: null, languages: ["TypeScript"], frameworks: [], packageManagers: ["npm"], entryPoints: ["src/cli.ts"], importantFiles: ["package.json"], buildCommands: ["npm run build"], testCommands: ["npm test"], verificationCommands: ["npm run check"], environmentRequirements: ["Node.js"], unknowns: [], discoveredAt: new Date().toISOString() }; await flow.ingest(value); expect((await flow.store.environment())?.status).toBe("pending-confirmation"); await flow.confirmEnvironment(); expect((await flow.store.environment())).toMatchObject({ revision: 2, status: "confirmed", languages: ["TypeScript"] }); await access(path.join(root, ".codegate", "environment", "facts-v2.json")); });
  it("versions a user learning profile independently from execution artifacts", async () => { const { root, flow } = await setup(); const profile = await flow.setLearningProfile({ level: "beginner", preferredDepth: "deep", knownTopics: [], learningGoals: ["understand reviews"], recurringConfusions: ["Git Diff"] }); expect(profile).toMatchObject({ revision: 1, level: "beginner" }); await access(path.join(root, ".codegate", "learning", "profile-v1.json")); });
  it("approves, hands off, accepts evidence, and unlocks the dependent step", async () => { const { root, flow } = await setup(); await flow.handoff("generic"); const value = report("passed"); await flow.ingest(value); const review = await flow.reviewWithPatch(value); expect(review.decision).toBe("accepted"); expect((await flow.store.state())).toMatchObject({ status: "step-ready", currentStepId: "step-002" }); expect((await flow.store.plan())?.steps[0]?.status).toBe("accepted"); await access(path.join(root, ".codegate", "plan", "patches", `review-${review.id}-plan-patch.json`)); });
  it("creates correction artifacts and immutable sequential handoffs when evidence is insufficient", async () => { const { root, flow } = await setup(); const original = await flow.handoff("codex"); const value = report("failed"); await flow.ingest(value); const review = await flow.reviewWithPatch(value); expect(review.decision).toBe("revision-required"); expect((await flow.store.state()).status).toBe("correction-ready"); await flow.correct("codex"); const first = JSON.parse(await readFile(path.join(root, ".codegate", "handoffs", "step-001-v1.json"), "utf8")); const second = JSON.parse(await readFile(path.join(root, ".codegate", "handoffs", "step-001-v2.json"), "utf8")); expect(first.content).toBe(original.content); expect(second.content).toContain("Correction Requirements"); expect((await flow.store.plan())?.steps[0]?.status).toBe("handed-off"); });
  it("rejects a report that cites a Handoff version that was never issued", async () => { const { flow } = await setup(); await flow.handoff("generic"); const value = report("passed"); value.handoffVersion = 99; await expect(flow.ingest(value)).rejects.toThrow("Handoff 不存在"); });
  it("rejects a claimed passing command when its log attachment is absent", async () => { const { flow } = await setup(); await flow.handoff("generic"); const value = report("passed"); value.commandsRun[0]!.outputArtifact = ".codegate/agent-reports/attachments/missing.log"; await flow.ingest(value); expect((await flow.reviewWithEvidence(value)).decision).toBe("revision-required"); });
});
