import { z } from "zod";

const text = z.string().trim().min(1);
const time = z.string().datetime({ offset: true });
const version = z.number().int().positive();
export const sourcePointerSchema = z.object({ sourceId: text, sourceType: z.enum(["user-message", "document", "image", "workspace-file", "external-link"]), locator: text, contentHash: text.optional() }).strict();
const cited = z.object({ id: text, description: text, sourcePointers: z.array(sourcePointerSchema).min(1) }).strict();
export const taskSpecSchema = z.object({
  id: text, version, title: text, objective: text,
  deliverables: z.array(cited.extend({ required: z.boolean() })),
  requirements: z.array(cited.extend({ priority: z.enum(["must", "should", "could"]) })),
  constraints: z.array(cited.extend({ hard: z.boolean() })),
  nonGoals: z.array(text), assumptions: z.array(z.object({ id: text, description: text, status: z.enum(["unconfirmed", "confirmed", "rejected"]) }).strict()),
  openQuestions: z.array(z.object({ id: text, question: text, impact: text, blocking: z.boolean(), answer: z.string().nullable() }).strict()),
  acceptanceCriteria: z.array(cited.extend({ title: text, required: z.boolean(), verificationMethod: z.enum(["command", "artifact-review", "manual-review", "user-confirmation"]), expectedEvidence: z.array(text) })),
  rubricItems: z.array(cited.extend({ score: z.number().positive().optional(), mappedRequirementIds: z.array(text), mappedDeliverableIds: z.array(text), mappedStepIds: z.array(text), status: z.enum(["unmapped", "planned", "implemented", "verified"]) })),
  sourceMaterialIds: z.array(text), createdAt: time, updatedAt: time,
}).strict();
export const architectureDecisionSchema = z.object({ id: text, version, title: text, status: z.enum(["proposed", "accepted", "rejected", "superseded"]), context: text, decision: text, alternatives: z.array(z.object({ name: text, advantages: z.array(text), disadvantages: z.array(text), rejectionReason: z.string().optional() }).strict()), consequences: z.array(text), affectedStepIds: z.array(text), sourcePointers: z.array(sourcePointerSchema), createdAt: time }).strict();
export const planStepSchema = z.object({ id: text, title: text, objective: text, rationale: text, dependencyStepIds: z.array(text), requirementIds: z.array(text), deliverableIds: z.array(text), acceptanceIds: z.array(text), rubricItemIds: z.array(text), architectureDecisionIds: z.array(text), recommendedSkillIds: z.array(text), expectedInputs: z.array(text), expectedOutputs: z.array(text), verificationInstructions: z.array(text), stopConditions: z.array(text), status: z.enum(["pending", "ready", "handed-off", "running", "reported", "under-review", "revision-required", "accepted", "blocked"]) }).strict();
export const workPlanSchema = z.object({ id: text, version, taskSpecVersion: version, summary: text, stepIds: z.array(text), status: z.enum(["draft", "approved", "executing", "completed"]), steps: z.array(planStepSchema), risks: z.array(text), createdAt: time, updatedAt: time }).strict();
export const handoffSchema = z.object({ id: text, version, stepId: text, taskSpecVersion: version, workPlanVersion: version, agentAdapter: z.enum(["generic", "codex", "claude-code"]), content: text, selectedSkillIds: z.array(text), inputRefs: z.array(text), createdAt: time }).strict();
export const projectEnvironmentFactsSchema = z.object({ revision: version, status: z.enum(["pending-confirmation", "confirmed", "stale"]), discoveredBy: text, sourceRevision: z.string().nullable(), languages: z.array(text), frameworks: z.array(text), packageManagers: z.array(text), entryPoints: z.array(text), importantFiles: z.array(text), buildCommands: z.array(text), testCommands: z.array(text), verificationCommands: z.array(text), environmentRequirements: z.array(text), unknowns: z.array(text), discoveredAt: time }).strict();
export const environmentObservationSchema = projectEnvironmentFactsSchema.omit({ revision: true, status: true });
export const executionReportSchema = z.object({ reportId: text, stepId: text, handoffVersion: version, agent: z.object({ name: text, model: z.string().optional(), sessionId: z.string().optional() }).strict(), status: z.enum(["completed", "partial", "blocked", "failed"]), summary: text, filesRead: z.array(text), filesChanged: z.array(text), commandsRun: z.array(z.object({ command: text, exitCode: z.number().int().nullable(), status: z.enum(["passed", "failed", "timed-out", "not-run"]), outputArtifact: z.string().optional() }).strict()), outputs: z.array(z.object({ type: text, path: z.string().optional(), description: text }).strict()), assumptions: z.array(text), risks: z.array(text), unresolvedItems: z.array(text), deviations: z.array(z.object({ description: text, reason: text }).strict()), recommendedNextAction: text, environmentFacts: environmentObservationSchema.optional(), generatedAt: time }).strict();
export const reviewReportSchema = z.object({ id: text, stepId: text, decision: z.enum(["accepted", "revision-required", "user-decision-required", "blocked"]), summary: text, acceptanceCoverage: z.array(z.object({ id: text, status: z.enum(["covered", "unverified", "missing"]), evidence: z.array(text), explanation: text }).strict()), driftFindings: z.array(z.object({ type: z.enum(["goal-drift", "scope-expansion", "architecture-drift", "requirement-omission", "rubric-omission", "verification-gap", "report-mismatch", "plan-obsolescence"]), description: text, evidence: z.array(text) }).strict()), unresolvedItems: z.array(text), correctionPatchId: z.string().optional(), generatedAt: time }).strict();
export const correctionPatchSchema = z.object({ id: text, stepId: text, reviewId: text, diagnosis: text, mustPreserve: z.array(text), mustChange: z.array(text), mustNotChange: z.array(text), additionalVerification: z.array(text), requiresUserDecision: z.boolean(), createdAt: time }).strict();
export const planPatchSchema = z.object({ id: text, basePlanVersion: version, targetPlanVersion: version, reason: text, triggeredBy: z.enum(["user", "review", "agent-report", "source-update"]), operations: z.array(z.object({ type: z.enum(["set-step-status", "unlock-step", "add-step", "adjust-dependencies"]), stepId: z.string().optional(), description: text }).strict()).min(1), affectedStepIds: z.array(text), requiresUserApproval: z.boolean(), createdAt: time }).strict();
export const skillManifestSchema = z.object({ id: text, version: text, name: text, description: text, applicableWhen: z.array(text).min(1), incompatibleWhen: z.array(text), requiredInputs: z.array(text), optionalInputs: z.array(text), procedure: z.array(z.object({ id: text, instruction: text, output: text }).strict()).min(1), qualityGates: z.array(text).min(1), antiPatterns: z.array(text), outputContract: z.record(text, z.unknown()), promptFragments: z.object({ leader: z.string().optional(), agent: z.string().optional(), reviewer: z.string().optional(), mentor: z.string().optional() }).strict() }).strict();
export const leaderAnalysisSchema = z.object({ summary: text, questions: z.array(z.object({ question: text, impact: text, blocking: z.boolean() }).strict()), architectureAlternatives: z.array(z.object({ name: text, advantages: z.array(text), disadvantages: z.array(text), recommendation: z.boolean() }).strict()), assumptions: z.array(text) }).strict();
export const learningProfileSchema = z.object({ revision: version, level: z.enum(["beginner", "intermediate", "advanced"]), preferredDepth: z.enum(["concise", "standard", "deep"]), knownTopics: z.array(text), learningGoals: z.array(text), recurringConfusions: z.array(text), updatedAt: time }).strict();
export const stateSchema = z.object({ schemaVersion: z.literal(1), status: z.enum(["new", "intake", "clarification-required", "task-spec-ready", "architecture-review", "plan-ready", "step-ready", "handed-off", "result-reported", "under-review", "correction-ready", "user-decision-required", "blocked", "task-completed"]), taskId: z.string().nullable(), taskSpecVersion: z.number().nullable(), workPlanVersion: z.number().nullable(), currentStepId: z.string().nullable(), updatedAt: time }).strict();
export type TaskSpec = z.infer<typeof taskSpecSchema>; export type ArchitectureDecision = z.infer<typeof architectureDecisionSchema>; export type WorkPlan = z.infer<typeof workPlanSchema>; export type Handoff = z.infer<typeof handoffSchema>; export type ExecutionReport = z.infer<typeof executionReportSchema>; export type ProjectEnvironmentFacts = z.infer<typeof projectEnvironmentFactsSchema>; export type ReviewReport = z.infer<typeof reviewReportSchema>; export type CorrectionPatch = z.infer<typeof correctionPatchSchema>; export type SkillManifest = z.infer<typeof skillManifestSchema>; export type LeaderAnalysis = z.infer<typeof leaderAnalysisSchema>; export type LearningProfile = z.infer<typeof learningProfileSchema>; export type LeaderState = z.infer<typeof stateSchema>;
