import { z } from "zod";

const text = z.string().trim().min(1);
const time = z.string().datetime({ offset: true });
const version = z.number().int().positive();
export const sourcePointerSchema = z.object({ sourceId: text, sourceType: z.enum(["user-message", "document", "image", "workspace-file", "external-link"]), locator: text, contentHash: text.optional() }).strict();
const cited = z.object({ id: text, description: text, sourcePointers: z.array(sourcePointerSchema).min(1) }).strict();
export const competitionMetricSchema = z.object({ id: text, label: text, target: z.string().optional(), unit: z.string().optional(), direction: z.enum(["higher", "lower", "pass", "range"]), evidence: z.array(text), sourcePointers: z.array(sourcePointerSchema).min(1) }).strict();
export const competitionProfileSchema = z.object({
  contestName: text, track: text, sourceFile: text, challengeId: text, challengeTitle: text,
  category: z.enum(["fpga-cpu", "fpga-accelerator", "fpga-vision", "fpga-ai", "sopc-open", "embedded", "algorithm", "other"]),
  selectionConfirmed: z.boolean().default(false),
  availableChallenges: z.array(z.object({ id: text, title: text }).strict()),
  boards: z.array(text), selectedBoard: z.string().nullable(), toolchains: z.array(text), languages: z.array(text),
  basicTasks: z.array(text), advancedTasks: z.array(text), metrics: z.array(competitionMetricSchema),
  submissionItems: z.array(text), demoRequirements: z.array(text), risks: z.array(text)
}).strict();
export const taskSpecSchema = z.object({
  id: text, version, title: text, objective: text,
  mode: z.enum(["product", "competition"]).optional(), competition: competitionProfileSchema.optional(),
  deliverables: z.array(cited.extend({ required: z.boolean() })),
  requirements: z.array(cited.extend({ priority: z.enum(["must", "should", "could"]) })),
  constraints: z.array(cited.extend({ hard: z.boolean() })),
  nonGoals: z.array(text), assumptions: z.array(z.object({ id: text, description: text, status: z.enum(["unconfirmed", "confirmed", "rejected"]) }).strict()),
  openQuestions: z.array(z.object({ id: text, question: text, impact: text, blocking: z.boolean(), answer: z.string().nullable() }).strict()),
  acceptanceCriteria: z.array(cited.extend({ title: text, required: z.boolean(), verificationMethod: z.enum(["command", "artifact-review", "manual-review", "user-confirmation"]), expectedEvidence: z.array(text) })),
  rubricItems: z.array(cited.extend({ score: z.number().positive().optional(), mappedRequirementIds: z.array(text), mappedDeliverableIds: z.array(text), mappedStepIds: z.array(text), status: z.enum(["unmapped", "planned", "implemented", "verified"]) })),
  sourceMaterialIds: z.array(text), createdAt: time, updatedAt: time,
}).strict();
export const architectureDecisionSchema = z.object({ id: text, version, title: text, status: z.enum(["proposed", "accepted", "rejected", "superseded"]), context: text, decision: text, alternatives: z.array(z.object({ name: text, advantages: z.array(text), disadvantages: z.array(text), rejectionReason: z.string().optional() }).strict()), consequences: z.array(text), affectedStepIds: z.array(text), sourcePointers: z.array(sourcePointerSchema), createdAt: time }).strict();
export const skillSelectionSchema = z.object({ skillId: text, reason: text }).strict();
export const planStepSchema = z.object({ id: text, title: text, objective: text, rationale: text, dependencyStepIds: z.array(text), requirementIds: z.array(text), deliverableIds: z.array(text), acceptanceIds: z.array(text), rubricItemIds: z.array(text), architectureDecisionIds: z.array(text), recommendedSkillIds: z.array(text), skillSelections: z.array(skillSelectionSchema).optional(), expectedInputs: z.array(text), expectedOutputs: z.array(text), verificationInstructions: z.array(text), stopConditions: z.array(text), status: z.enum(["pending", "ready", "handed-off", "running", "reported", "under-review", "revision-required", "accepted", "blocked", "abandoned"]) }).strict();
export const workPlanSchema = z.object({ id: text, version, taskSpecVersion: version, summary: text, stepIds: z.array(text), status: z.enum(["draft", "approved", "executing", "completed", "superseded"]), steps: z.array(planStepSchema), risks: z.array(text), createdAt: time, updatedAt: time }).strict();
export const handoffSchema = z.object({ id: text, version, stepId: text, taskSpecVersion: version, workPlanVersion: version, agentAdapter: z.enum(["generic", "codex", "claude-code"]), content: text, selectedSkillIds: z.array(text), inputRefs: z.array(text), createdAt: time }).strict();
export const projectEnvironmentFactsSchema = z.object({ revision: version, status: z.enum(["pending-confirmation", "confirmed", "stale"]), discoveredBy: text, sourceRevision: z.string().nullable(), languages: z.array(text), frameworks: z.array(text), packageManagers: z.array(text), entryPoints: z.array(text), importantFiles: z.array(text), buildCommands: z.array(text), testCommands: z.array(text), verificationCommands: z.array(text), environmentRequirements: z.array(text), unknowns: z.array(text), discoveredAt: time }).strict();
export const environmentObservationSchema = projectEnvironmentFactsSchema.omit({ revision: true, status: true });
export const commandResultSchema = z.object({ command: text, exitCode: z.number().int().nullable(), status: z.enum(["passed", "failed", "timed-out", "not-run"]), outputArtifact: z.string().optional(), outputHash: z.string().optional(), coversAcceptanceIds: z.array(text).optional() }).strict();
export const executionReportSchema = z.object({ reportId: text, stepId: text, handoffVersion: version, agent: z.object({ name: text, model: z.string().optional(), sessionId: z.string().optional() }).strict(), status: z.enum(["completed", "partial", "blocked", "failed"]), summary: text, workspaceRevisionBefore: z.string().optional(), workspaceRevisionAfter: z.string().optional(), filesRead: z.array(text), filesChanged: z.array(text), commandsRun: z.array(commandResultSchema), outputs: z.array(z.object({ type: text, path: z.string().optional(), description: text, contentHash: z.string().optional(), coversRequirementIds: z.array(text).optional(), coversAcceptanceIds: z.array(text).optional(), coversRubricItemIds: z.array(text).optional() }).strict()), decisionsMade: z.array(z.object({ description: text, reason: text, requiresLeaderReview: z.boolean() }).strict()).optional(), assumptions: z.array(text), risks: z.array(text), unresolvedItems: z.array(text), deviations: z.array(z.object({ description: text, reason: text }).strict()), recommendedNextAction: text, environmentFacts: environmentObservationSchema.optional(), generatedAt: time }).strict();
export const verificationRunSchema = z.object({ id: text, source: z.literal("codegate"), stepId: text, handoffVersion: version, command: text, status: z.enum(["passed", "failed", "timed-out"]), exitCode: z.number().int().nullable(), signal: z.string().nullable(), outputArtifact: text, outputHash: text, coversAcceptanceIds: z.array(text), startedAt: time, finishedAt: time, durationMs: z.number().int().nonnegative() }).strict();
export const coverageResultSchema = z.object({ id: text, status: z.enum(["covered", "unverified", "missing", "not-applicable"]), evidence: z.array(text), explanation: text }).strict();
export const reviewFindingSchema = z.object({ severity: z.enum(["info", "warning", "error"]), code: text, description: text, evidence: z.array(text) }).strict();
export const driftFindingSchema = z.object({ type: z.enum(["goal-drift", "scope-expansion", "architecture-drift", "requirement-omission", "rubric-omission", "verification-gap", "report-mismatch", "plan-obsolescence"]), description: text, evidence: z.array(text) }).strict();
export const reviewReportSchema = z.object({ id: text, stepId: text, handoffVersion: version.optional(), decision: z.enum(["accepted", "revision-required", "user-decision-required", "blocked"]), summary: text, requirementCoverage: z.array(coverageResultSchema).optional(), acceptanceCoverage: z.array(coverageResultSchema), rubricCoverage: z.array(coverageResultSchema).optional(), architectureFindings: z.array(reviewFindingSchema).optional(), implementationFindings: z.array(reviewFindingSchema).optional(), verificationFindings: z.array(reviewFindingSchema).optional(), driftFindings: z.array(driftFindingSchema), evidenceRefs: z.array(text).optional(), unresolvedItems: z.array(text), correctionPatchId: z.string().optional(), userDecisionRequestId: z.string().optional(), generatedAt: time }).strict();
export const correctionPatchSchema = z.object({ id: text, stepId: text, reviewId: text, diagnosis: text, mustPreserve: z.array(text), mustChange: z.array(text), mustNotChange: z.array(text), additionalVerification: z.array(text), requiresUserDecision: z.boolean(), createdAt: time }).strict();
export const planPatchOperationSchema = z.object({ type: z.enum(["set-step-status", "unlock-step", "add-step", "adjust-dependencies", "modify-step-objective", "add-acceptance-mapping", "add-risk", "abandon-step"]), stepId: z.string().optional(), description: text, status: planStepSchema.shape.status.optional(), step: planStepSchema.optional(), dependencyStepIds: z.array(text).optional(), objective: z.string().optional(), acceptanceIds: z.array(text).optional(), risk: z.string().optional() }).strict();
export const planPatchSchema = z.object({ id: text, basePlanVersion: version, targetPlanVersion: version, reason: text, triggeredBy: z.enum(["user", "review", "agent-report", "source-update"]), operations: z.array(planPatchOperationSchema).min(1), affectedStepIds: z.array(text), requiresUserApproval: z.boolean(), createdAt: time }).strict();
export const skillManifestSchema = z.object({ id: text, version: text, name: text, description: text, applicableWhen: z.array(text).min(1), incompatibleWhen: z.array(text), requiredInputs: z.array(text), optionalInputs: z.array(text), procedure: z.array(z.object({ id: text, instruction: text, output: text }).strict()).min(1), qualityGates: z.array(text).min(1), antiPatterns: z.array(text), outputContract: z.record(text, z.unknown()), promptFragments: z.object({ leader: z.string().optional(), agent: z.string().optional(), reviewer: z.string().optional(), mentor: z.string().optional() }).strict() }).strict();
export const leaderAnalysisSchema = z.object({ summary: text, questions: z.array(z.object({ question: text, impact: text, blocking: z.boolean() }).strict()), architectureAlternatives: z.array(z.object({ name: text, advantages: z.array(text), disadvantages: z.array(text), recommendation: z.boolean() }).strict()), assumptions: z.array(text) }).strict();
export const semanticReviewSchema = z.object({ architectureFindings: z.array(reviewFindingSchema), implementationFindings: z.array(reviewFindingSchema), driftFindings: z.array(driftFindingSchema), requiresUserDecision: z.boolean(), summary: text }).strict();
export const learningProfileSchema = z.object({ revision: version, level: z.enum(["beginner", "intermediate", "advanced"]), preferredDepth: z.enum(["concise", "standard", "deep"]), knownTopics: z.array(text), learningGoals: z.array(text), recurringConfusions: z.array(text), updatedAt: time }).strict();
export const workspaceBaselineSchema = z.object({ id: text, stepId: text, handoffVersion: version, headRevision: z.string().nullable(), changedFiles: z.array(text), fileHashes: z.record(text, z.string()), createdAt: time }).strict();
export const userDecisionRequestSchema = z.object({ id: text, kind: z.enum(["scope-change", "architecture-change", "evidence-conflict", "repeated-drift"]), stepId: text, reviewId: text, status: z.enum(["pending", "resolved"]), question: text, context: text, options: z.array(z.enum(["accept-current", "request-correction", "update-plan", "block"])).min(1), resolution: z.enum(["accept-current", "request-correction", "update-plan", "block"]).nullable(), createdAt: time, resolvedAt: z.string().datetime({ offset: true }).nullable() }).strict();
export const protocolManifestSchema = z.object({ protocolVersion: z.literal(2), productVersion: text, workspaceRoot: text, createdAt: time, updatedAt: time }).strict();
export const stateSchema = z.object({ schemaVersion: z.literal(2), status: z.enum(["new", "intake", "clarification-required", "task-spec-ready", "architecture-review", "plan-ready", "step-ready", "handed-off", "result-reported", "under-review", "correction-ready", "user-decision-required", "blocked", "task-completed"]), taskId: z.string().nullable(), taskSpecVersion: z.number().nullable(), workPlanVersion: z.number().nullable(), currentStepId: z.string().nullable(), pendingDecisionId: z.string().nullable(), updatedAt: time }).strict();
export const assistantMessageSchema = z.object({ id: text, role: z.enum(["user", "leader"]), content: text, state: stateSchema.shape.status, createdAt: time }).strict();
export const modelUsageSchema = z.object({ id: text, operation: z.enum(["consult", "analysis", "mentor", "review"]), model: text, promptTokens: z.number().int().nonnegative(), completionTokens: z.number().int().nonnegative(), totalTokens: z.number().int().nonnegative(), estimatedCostUsd: z.number().nonnegative().nullable(), createdAt: time }).strict();
export const projectConfigSchema = z.object({ mode: z.enum(["product", "competition"]), createdAt: time, updatedAt: time }).strict();
export const competitionDebugSessionSchema = z.object({ id: text, category: z.enum(["compile", "simulation", "synthesis", "implementation", "timing", "constraint", "programming", "hardware", "resource", "performance", "unknown"]), symptom: text, log: text, diagnosis: text, fixPrompt: text, status: z.enum(["open", "resolved"]), stepId: z.string().nullable(), resolution: z.string().nullable(), evidence: z.array(text), createdAt: time, resolvedAt: z.string().datetime({ offset: true }).nullable() }).strict();
export const competitionMetricRecordSchema = z.object({ id: text, metricId: text, label: text, value: z.number(), unit: text, context: z.string(), evidence: z.array(text), recordedAt: time }).strict();
export const competitionDefenseSessionSchema = z.object({ id: text, questions: z.array(z.object({ id: text, question: text, rationale: text, focus: z.enum(["architecture", "algorithm", "timing", "resource", "verification", "robustness", "delivery"]), answer: z.string().nullable(), assessment: z.string().nullable() }).strict()).min(1), createdAt: time }).strict();
export type SourcePointer = z.infer<typeof sourcePointerSchema>; export type TaskSpec = z.infer<typeof taskSpecSchema>; export type ArchitectureDecision = z.infer<typeof architectureDecisionSchema>; export type WorkPlan = z.infer<typeof workPlanSchema>; export type PlanPatch = z.infer<typeof planPatchSchema>; export type Handoff = z.infer<typeof handoffSchema>; export type ExecutionReport = z.infer<typeof executionReportSchema>; export type VerificationRun = z.infer<typeof verificationRunSchema>; export type ProjectEnvironmentFacts = z.infer<typeof projectEnvironmentFactsSchema>; export type ReviewReport = z.infer<typeof reviewReportSchema>; export type CorrectionPatch = z.infer<typeof correctionPatchSchema>; export type SkillManifest = z.infer<typeof skillManifestSchema>; export type LeaderAnalysis = z.infer<typeof leaderAnalysisSchema>; export type SemanticReview = z.infer<typeof semanticReviewSchema>; export type LearningProfile = z.infer<typeof learningProfileSchema>; export type AssistantMessage = z.infer<typeof assistantMessageSchema>; export type ModelUsage = z.infer<typeof modelUsageSchema>; export type LeaderState = z.infer<typeof stateSchema>; export type WorkspaceBaseline = z.infer<typeof workspaceBaselineSchema>; export type UserDecisionRequest = z.infer<typeof userDecisionRequestSchema>; export type ProtocolManifest = z.infer<typeof protocolManifestSchema>; export type CompetitionProfile = z.infer<typeof competitionProfileSchema>; export type CompetitionDebugSession = z.infer<typeof competitionDebugSessionSchema>; export type CompetitionMetricRecord = z.infer<typeof competitionMetricRecordSchema>; export type CompetitionDefenseSession = z.infer<typeof competitionDefenseSessionSchema>; export type ProjectConfig = z.infer<typeof projectConfigSchema>;
