#!/usr/bin/env node
import { Command } from "commander";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { executionReportSchema, planPatchSchema, taskSpecSchema } from "./core/schemas.js";
import { LeaderWorkflow } from "./core/workflow.js";
import { evaluateComparativeRuns } from "./core/evaluation.js";

const program = new Command().name("codegate").description("CodeGate Leader: task facts, handoff, review, and mentoring.");
const root = () => process.cwd();
const workflow = () => new LeaderWorkflow(root());
program.command("init").action(async () => { await workflow().init(); console.log(`Initialized ${path.join(root(), ".codegate")}`); });
program.command("intake <taskFile>").action(async (taskFile) => { const task = await workflow().intake(taskFile); console.log(JSON.stringify(task, null, 2)); });
program.command("add-source <sourceFile>").action(async (sourceFile) => console.log(JSON.stringify(await workflow().addSourceMaterial(sourceFile), null, 2)));
program.command("approve-task").action(async () => { await workflow().approveTask(); console.log("TaskSpec approved."); });
program.command("clarify <questionId> <answer>").action(async (questionId, answer) => { console.log(JSON.stringify(await workflow().clarify(questionId, answer), null, 2)); });
program.command("leader-analyze [message]").action(async (message) => { console.log(JSON.stringify(await workflow().analyzeWithLeader(message), null, 2)); });
program.command("learning-profile <level> <depth>").option("--goals <items...>").option("--known <items...>").action(async (level, depth, options) => { console.log(JSON.stringify(await workflow().setLearningProfile({ level, preferredDepth: depth, learningGoals: options.goals ?? [], knownTopics: options.known ?? [], recurringConfusions: [] }), null, 2)); });
program.command("ask <question>").action(async (question) => console.log(await workflow().askMentor(question)));
program.command("update-task <taskSpecFile>").action(async (taskSpecFile) => { const task = taskSpecSchema.parse(JSON.parse(await readFile(path.resolve(root(), taskSpecFile), "utf8"))); await workflow().updateTask(task); console.log("TaskSpec revision saved."); });
program.command("reopen-task <reason>").action(async (reason) => console.log(JSON.stringify(await workflow().reopenTask(reason), null, 2)));
program.command("architecture <title> <decision>").action(async (title, decision) => { await workflow().architecture(title, decision); console.log("Architecture decision recorded."); });
program.command("plan").action(async () => console.log(JSON.stringify(await workflow().createPlan(), null, 2)));
program.command("approve-plan").action(async () => { await workflow().approvePlanWithPatch(); console.log("WorkPlan approved."); });
program.command("patch-plan <patchFile>").option("--approve").action(async (patchFile, options) => { const patch = planPatchSchema.parse(JSON.parse(await readFile(path.resolve(root(), patchFile), "utf8"))); console.log(JSON.stringify(await workflow().applyPlanPatch(patch, Boolean(options.approve)), null, 2)); });
program.command("status").action(async () => { const flow = workflow(); await flow.init(); console.log(JSON.stringify(await flow.store.state(), null, 2)); });
program.command("next").requiredOption("--agent <generic|codex|claude>").action(async (options) => { const adapter = options.agent === "claude" ? "claude-code" : options.agent; if (!(["generic", "codex", "claude-code"] as const).includes(adapter)) throw new Error("agent must be generic, codex, or claude"); const handoff = await workflow().handoff(adapter); console.log(handoff.content); });
program.command("export-handoff [stepId]").action(async (stepId) => { const flow = workflow(); const state = await flow.store.state(); const handoff = await flow.store.latestHandoff(stepId ?? state.currentStepId ?? ""); if (!handoff) throw new Error("未找到可导出的 Handoff。"); console.log(handoff.content); });
program.command("ingest <reportFile>").action(async (reportFile) => { const report = executionReportSchema.parse(JSON.parse(await readFile(path.resolve(root(), reportFile), "utf8"))); await workflow().ingest(report); console.log("Execution Report imported."); });
program.command("confirm-environment").action(async () => { await workflow().confirmEnvironment(); console.log("Environment facts confirmed."); });
program.command("verify <command>").requiredOption("--yes", "confirm execution of the exact approved command").action(async (command) => { console.log(JSON.stringify(await workflow().runVerification(command, true), null, 2)); });
program.command("review <reportFile>").action(async (reportFile) => { const report = executionReportSchema.parse(JSON.parse(await readFile(path.resolve(root(), reportFile), "utf8"))); console.log(JSON.stringify(await workflow().reviewWithEvidence(report), null, 2)); });
program.command("correct").requiredOption("--agent <generic|codex|claude>").action(async (options) => { const adapter = options.agent === "claude" ? "claude-code" : options.agent; if (!( ["generic", "codex", "claude-code"] as const).includes(adapter)) throw new Error("agent must be generic, codex, or claude"); console.log(await workflow().correct(adapter)); });
program.command("decide <decisionId> <resolution>").action(async (decisionId, resolution) => { const allowed = ["accept-current", "request-correction", "update-plan", "block"] as const; if (!allowed.includes(resolution)) throw new Error("resolution must be accept-current, request-correction, update-plan, or block"); console.log(JSON.stringify(await workflow().resolveDecision(decisionId, resolution), null, 2)); });
program.command("explain").action(async () => console.log(await workflow().explain()));
program.command("evaluate <resultsFile>").action(async (resultsFile) => console.log(JSON.stringify(evaluateComparativeRuns(JSON.parse(await readFile(path.resolve(root(), resultsFile), "utf8"))), null, 2)));
program.parseAsync().catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
